### ISSUE TITLE
Request license

### ISSUE THREAD

**Issue by songsammy** [Quinten/black-hole-square#1]
For any open source project, license is a must. I'd like to use this project and I want to be sure that I am allowed to do so, like publishing a modified version.  
You may refer to https://choosealicense.com/

**Comment by Quinten** [comment]
It is intentional that there is no license. This repository is only for demonstration purposes and for others to learn from. You are free to use small portions of the code, but you cannot copy the project as a whole or just slap another name on it.

I like to point out that game mechanics cannot be copyrighted, but names, graphics, story, copywriting etc can be...

**Comment by Quinten** [comment]
@songsammy sorry, i changed my mind. I added the MIT license. Hope that fits your use case...
